#!/usr/bin/env python3
"""
test_workload_generator.py - Focused tests for Workload Generator.

Validates:
1. Rejects non-empty target directory before touching anything.
2. Rejects symlink target directories.
3. Supports paths with spaces cleanly.
4. Deterministic Git object IDs (HEAD OID, commit OID) with identical seed.
5. Rich Git states (staged, unstaged, untracked, samepath stagedAworkingB, rename, delete).
6. Exact counts on medium preset (15 repos, exact commit/ref/path counts matching manifest).
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest

SCRIPTS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)

from workload_generator import generate_workload


class TestWorkloadGenerator(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()

    def tearDown(self) -> None:
        self.temp_dir.cleanup()

    def test_reject_nonempty_target_dir(self) -> None:
        """Verify generator refuses to clobber a pre-existing non-empty directory."""
        target = os.path.join(self.temp_dir.name, "non_empty_dir")
        os.makedirs(target)
        existing_file = os.path.join(target, "user_precious_data.txt")
        with open(existing_file, "w") as f:
            f.write("Do not delete me!\n")

        with self.assertRaises(ValueError) as ctx:
            generate_workload(target_dir=target, preset="smoke")

        self.assertIn("not empty", str(ctx.exception))
        # Ensure user data was untouched
        self.assertTrue(os.path.exists(existing_file))
        with open(existing_file) as f:
            self.assertEqual(f.read(), "Do not delete me!\n")

    def test_reject_symlink_target(self) -> None:
        """Verify generator rejects a symlink target directory for safety."""
        real_target = os.path.join(self.temp_dir.name, "real_empty_dir")
        os.makedirs(real_target)
        symlink_target = os.path.join(self.temp_dir.name, "symlink_dir")
        os.symlink(real_target, symlink_target)

        with self.assertRaises(ValueError) as ctx:
            generate_workload(target_dir=symlink_target, preset="smoke")

        self.assertIn("symlink", str(ctx.exception))

    def test_spaces_in_target_dir(self) -> None:
        """Verify generator properly handles target paths containing spaces."""
        target_with_spaces = os.path.join(self.temp_dir.name, "snip workload path with spaces")
        manifest = generate_workload(
            target_dir=target_with_spaces,
            preset="smoke",
            quiet=True,
        )

        self.assertTrue(os.path.exists(target_with_spaces))
        self.assertEqual(manifest["summary"]["totalRepos"], 2)
        repo0 = manifest["repos"][0]
        self.assertTrue(os.path.isdir(repo0["path"]))
        self.assertIn("snip workload path with spaces", repo0["path"])

    def test_deterministic_git_object_ids(self) -> None:
        """
        Verify that two runs with the same seed generate 100% byte-identical
        Git object IDs (HEAD OIDs, commit counts, tree states).
        """
        dir1 = os.path.join(self.temp_dir.name, "run_1")
        dir2 = os.path.join(self.temp_dir.name, "run_2")

        m1 = generate_workload(target_dir=dir1, preset="smoke", seed=12345, quiet=True)
        m2 = generate_workload(target_dir=dir2, preset="smoke", seed=12345, quiet=True)

        self.assertEqual(len(m1["repos"]), len(m2["repos"]))
        for r1, r2 in zip(m1["repos"], m2["repos"]):
            self.assertEqual(r1["headOid"], r2["headOid"])
            self.assertEqual(r1["commitCount"], r2["commitCount"])
            self.assertEqual(r1["mergeCommitOid"], r2["mergeCommitOid"])
            self.assertEqual(r1["mergeParents"], r2["mergeParents"])
            self.assertEqual(r1["porcelainStatus"], r2["porcelainStatus"])

    def test_rich_git_states(self) -> None:
        """
        Verify that repo-01 generated by workload generator contains:
        - samepath staged A working B
        - staged rename
        - staged delete
        - unstaged delete
        - staged new file
        - unstaged change
        - untracked file
        - merge commit with >= 2 parents
        """
        target = os.path.join(self.temp_dir.name, "state_test")
        manifest = generate_workload(target_dir=target, preset="smoke", quiet=True)

        repo0 = manifest["repos"][0]
        r0_path = repo0["path"]

        # Run git status --porcelain directly in repo0 to verify oracle
        status = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=r0_path,
            capture_output=True,
            text=True,
            check=True,
        ).stdout

        # 1. samepath stagedAworkingB has 'MM'
        self.assertIn("MM src/staged_and_working.ts", status)

        # Verify staged vs working content differ:
        diff_cached = subprocess.run(
            ["git", "diff", "--cached", "src/staged_and_working.ts"],
            cwd=r0_path,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
        self.assertIn("Version A", diff_cached)

        diff_working = subprocess.run(
            ["git", "diff", "src/staged_and_working.ts"],
            cwd=r0_path,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
        self.assertIn("Version B", diff_working)

        # 2. Staged rename
        self.assertIn("R  src/rename_src.ts -> src/rename_dest.ts", status)

        # 3. Staged delete
        self.assertIn("D  src/delete_staged.ts", status)

        # 4. Unstaged delete
        self.assertIn(" D src/delete_unstaged.ts", status)

        # 5. Staged new file
        self.assertIn("A  src/new_staged_feature.ts", status)

        # 6. Unstaged modification
        self.assertIn(" M README.md", status)

        # 7. Untracked files
        self.assertIn("?? .env.local", status)

        # 8. Merge commit has 2 parents
        self.assertTrue(repo0["hasMergeCommit"])
        self.assertEqual(len(repo0["mergeParents"]), 2)

    def test_medium_preset_exactcounts_check(self) -> None:
        """
        Verify medium preset generates exact counts:
        - 15 repositories
        - 60 commits per repo (900 total)
        - 10 refs per repo (150 total)
        - 100 tracked paths per repo
        - Manifest summary matches sum of repo metrics
        """
        target = os.path.join(self.temp_dir.name, "medium_workload")
        manifest = generate_workload(target_dir=target, preset="medium", quiet=True)

        self.assertEqual(manifest["preset"], "medium")
        repos = manifest["repos"]
        self.assertEqual(len(repos), 15)

        for r in repos:
            self.assertEqual(r["commitCount"], 60)
            self.assertEqual(r["refCount"], 10)
            self.assertEqual(r["trackedPathsCount"], 100)
            self.assertTrue(r["hasMergeCommit"])
            self.assertEqual(len(r["mergeParents"]), 2)

        summary = manifest["summary"]
        self.assertEqual(summary["totalRepos"], 15)
        self.assertEqual(summary["totalCommits"], 15 * 60)
        self.assertEqual(summary["totalRefs"], 15 * 10)
        self.assertEqual(summary["totalTrackedPaths"], 15 * 100)

        # Verify state counts are non-zero
        self.assertGreater(summary["stagedCount"], 0)
        self.assertGreater(summary["unstagedCount"], 0)
        self.assertGreater(summary["untrackedCount"], 0)
        self.assertGreater(summary["stagedAWorkingBCount"], 0)
        self.assertGreater(summary["renameCount"], 0)
        self.assertGreater(summary["deleteCount"], 0)

        # Verify manifest file on disk matches returned manifest
        manifest_file = os.path.join(target, "workload_manifest.json")
        self.assertTrue(os.path.exists(manifest_file))
        with open(manifest_file, "r") as f:
            disk_data = json.load(f)
        self.assertEqual(disk_data["summary"], summary)


if __name__ == "__main__":
    unittest.main()
